#!/bin/bash
# https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

git pull

source .venv/bin/activate
pip3 install -r requirements.txt

date > lastReboot.txt
/usr/bin/reboot
