#!/bin/bash
killall python
killall chromium-browser
cd /home/meteohub/KEGWeatherHist

source .venv/bin/activate

pip install pyautogui
python -c "import pyautogui; pyautogui.moveTo(0,0);"

python start.py &
echo -------------------------------------------------------------------------
echo Startet in 60 s
echo -------------------------------------------------------------------------
sleep 60

chromium-browser --chrome --kiosk http://amorkeg.de/wetter/meteoware.html --no-sandbox --force-device-scale-factor=1.5

