name: publish

on: [release]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build the docker image
              run: |
                  echo $CR_PAT | docker login ghcr.io -u PaddeCraft --password-stdin
                  docker build -t ghcr.io/PaddeCraft/keg-weather-history-webserver:latest .
                  docker push ghcr.io/PaddeCraft/keg-weather-history-webserver:latest
              env:
                  CR_PAT: ${{ secrets.CR_PAT }}
